# Generated by Django 3.2 on 2022-03-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
